### ISSUE TITLE
I'm back =)

### ISSUE THREAD

**Issue by vespakoen** [mtscout6/react-router-bootstrap#19]
Hey there!

I have been into deep rabbit holes and havn't really been able to look around outside to see what has been going on.

I've seen you have updated the library and cleaned / improved it a lot, that's awesome!

I am wondering how you are handling the "reserved props" / filtering out the "non-parameters".
I was planning on removing all that checking stuff and moving to a params={{some: 'param'}} way of doing things, but it seems you find a way to make it work anyhow, now I am wondering how you did it =)

Can you point me to the relevant code?

Keep up the good work! I'll try to get involved in in proving the library further

**Comment by mtscout6** [comment]
The newer versions of react-router are no longer pulling all the props instead you use the prop params to, so no need to filter out params any more.

Also, take note that we are now using the `--harmony` features for jsx in our [`npm run build`](https://github.com/mtscout6/react-router-bootstrap/blob/master/package.json#L8) command. This means we get object [destructuring in the MenuItemLink](https://github.com/mtscout6/react-router-bootstrap/blob/master/src/MenuItemLink.js#L15-L21), as an example. Those values are taken off the original props, and the [`...props`](https://github.com/mtscout6/react-router-bootstrap/blob/master/src/MenuItemLink.js#L21) will be whatever is left. This way we don't send `to`, `params`, `query`, `active`, or `onSelect` in the case of the `MenuItemLink` to the `MenuItem`. This is also possible because the of the [`{...props}`](https://github.com/mtscout6/react-router-bootstrap/blob/master/src/MenuItemLink.js#L28) feature of jsx that I used which implicitly applies each object property to the child's props. You can read up on all of that  in [React's documentation](http://facebook.github.io/react/docs/transferring-props.html).

Lastly I pulled the shared code out to a [mixin](https://github.com/mtscout6/react-router-bootstrap/blob/master/src/MenuItemLink.js#L9), instead of using a helper file.

**Comment by vespakoen** [comment]
Ha!, great! thanks for the explaination!

**Comment by mtscout6** [comment]
No problem
